name: Compilar Reporte LaTeX

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Documentation/Reporte#1/**'
  workflow_dispatch:

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Compilar documento LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Compilers_Proyect_Report.tex
          working_directory: 'Documentation/Reporte#1'

      - name: Subir PDF generado como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: Compilers_Proyect_Report
          path: 'Documentation/Reporte#1/Compilers_Proyect_Report.pdf'